In [58]:
%load_ext autoreload
%autoreload 2
import pandas as pd

df = pd.read_excel("../data/archetypes_v1.xlsx", index_col=0)
df.head()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

,usage,residential,building_period,renovation,energy_carrier_primary,Af_m2,Aroof_m2,GFA_m2,Aocc_m2,people0,E_final_heating_MWhyr,E_final_dhw_MWhyr,E_final_cooling_MWhyr,E_final_user_MWhyr,E_therm_MWhyr,Q_use_heating_MWhyr,Q_use_dhw_MWhyr,Q_use_cooling_MWhyr,Q_use_user_MWhyr
archetype_id,,,,,,,,,,,,,,,,,,,
EFH I_Bis 1919_biogene,sfh,yes,bis 1919,no,biogene,210.08,103.9,366.5,208.0,2.97,83.852918,9.104442,0.0,9.002447,92.957360,62.889689,6.828332,0.0,9.002447
EFH I_Bis 1919_dh,sfh,yes,bis 1919,no,district_heating,210.08,103.9,366.5,208.0,2.97,64.173152,6.967685,0.0,9.002447,71.140837,62.889689,6.828332,0.0,9.002447
EFH I_Bis 1919_fossil,sfh,yes,bis 1919,no,fossil,210.08,103.9,366.5,208.0,2.97,78.612111,8.535414,0.0,9.002447,87.147525,62.889689,6.828332,0.0,9.002447
EFH I_Bis 1919_hp,sfh,yes,bis 1919,no,heatpump,210.08,103.9,366.5,208.0,2.97,20.963230,2.276111,0.0,9.002447,23.239340,62.889689,6.828332,0.0,9.002447
EFH I_Bis 1919_reno_biogene,sfh,yes,bis 1919,yes,biogene,210.08,103.9,366.5,208.0,2.97,20.081001,9.014693,0.0,9.002447,29.095694,15.060751,6.761020,0.0,9.002447

In [59]:
from archifer.model import BuildingSector

bs = BuildingSector(df)
bs.ids

['EFH I_Bis 1919_biogene',
 'EFH I_Bis 1919_dh',
 'EFH I_Bis 1919_fossil',
 'EFH I_Bis 1919_hp',
 'EFH I_Bis 1919_reno_biogene',
 'EFH I_Bis 1919_reno_dh',
 'EFH I_Bis 1919_reno_fossil',
 'EFH I_Bis 1919_reno_hp',
 'EFH II_1920-44_biogene',
 'EFH II_1920-44_dh',
 'EFH II_1920-44_fossil',
 'EFH II_1920-44_hp',
 'EFH II_1920-44_reno_biogene',
 'EFH II_1920-44_reno_dh',
 'EFH II_1920-44_reno_fossil',
 'EFH II_1920-44_reno_hp',
 'EFH III_1945-59_biogene',
 'EFH III_1945-59_dh',
 'EFH III_1945-59_fossil',
 'EFH III_1945-59_hp',
 'EFH III_1945-59_reno_biogene',
 'EFH III_1945-59_reno_dh',
 'EFH III_1945-59_reno_fossil',
 'EFH III_1945-59_reno_hp',
 'EFH IV_1960-79_biogene',
 'EFH IV_1960-79_dh',
 'EFH IV_1960-79_fossil',
 'EFH IV_1960-79_hp',
 'EFH IV_1960-79_reno_biogene',
 'EFH IV_1960-79_reno_dh',
 'EFH IV_1960-79_reno_fossil',
 'EFH IV_1960-79_reno_hp',
 'EFH V_1980-89_biogene',
 'EFH V_1980-89_dh',
 'EFH V_1980-89_fossil',
 'EFH V_1980-89_hp',
 'EFH V_1980-89_reno_biogene',
 'EFH V_1980-89_reno_dh',
 'EFH V_1980-89_reno_fossil',
 'EFH V_1980-89_reno_hp',
 'EFH VI_1990-99_biogene',
 'EFH VI_1990-99_dh',
 'EFH VI_1990-99_fossil',
 'EFH VI_1990-99_hp',
 'EFH VI_1990-99_reno_biogene',
 'EFH VI_1990-99_reno_dh',
 'EFH VI_1990-99_reno_fossil',
 'EFH VI_1990-99_reno_hp',
 'EFH VII_2000-20_biogene',
 'EFH VII_2000-20_dh',
 'EFH VII_2000-20_fossil',
 'EFH VII_2000-20_hp',
 'EFH VIII_>2020_biogene',
 'EFH VIII_>2020_dh',
 'EFH VIII_>2020_fossil',
 'EFH VIII_>2020_hp',
 'IWU Culture and Leisure (5) 1860 - 1978_biogene',
 'IWU Culture and Leisure (5) 1860 - 1978_dh',
 'IWU Culture and Leisure (5) 1860 - 1978_fossil',
 'IWU Culture and Leisure (5) 1860 - 1978_hp',
 'IWU Culture and Leisure (5) 1979 - 2009_biogene',
 'IWU Culture and Leisure (5) 1979 - 2009_dh',
 'IWU Culture and Leisure (5) 1979 - 2009_fossil',
 'IWU Culture and Leisure (5) 1979 - 2009_hp',
 'IWU Culture and Leisure (5) 2010 - 2030_biogene',
 'IWU Culture and Leisure (5) 2010 - 2030_dh',
 'IWU Culture and Leisure (5) 2010 - 2030_fossil',
 'IWU Culture and Leisure (5) 2010 - 2030_hp',
 'IWU Hotels, Boarding, Restaurants or Catering (7) 1860 - 1978_biogene',
 'IWU Hotels, Boarding, Restaurants or Catering (7) 1860 - 1978_dh',
 'IWU Hotels, Boarding, Restaurants or Catering (7) 1860 - 1978_fossil',
 'IWU Hotels, Boarding, Restaurants or Catering (7) 1860 - 1978_hp',
 'IWU Hotels, Boarding, Restaurants or Catering (7) 1979 - 2009_biogene',
 'IWU Hotels, Boarding, Restaurants or Catering (7) 1979 - 2009_dh',
 'IWU Hotels, Boarding, Restaurants or Catering (7) 1979 - 2009_fossil',
 'IWU Hotels, Boarding, Restaurants or Catering (7) 1979 - 2009_hp',
 'IWU Hotels, Boarding, Restaurants or Catering (7) 2010 - 2030_biogene',
 'IWU Hotels, Boarding, Restaurants or Catering (7) 2010 - 2030_dh',
 'IWU Hotels, Boarding, Restaurants or Catering (7) 2010 - 2030_fossil',
 'IWU Hotels, Boarding, Restaurants or Catering (7) 2010 - 2030_hp',
 'IWU Office, Administrative or Government Buildings 1860 - 1978_biogene',
 'IWU Office, Administrative or Government Buildings 1860 - 1978_dh',
 'IWU Office, Administrative or Government Buildings 1860 - 1978_fossil',
 'IWU Office, Administrative or Government Buildings 1860 - 1978_hp',
 'IWU Office, Administrative or Government Buildings 1979 - 2009_biogene',
 'IWU Office, Administrative or Government Buildings 1979 - 2009_dh',
 'IWU Office, Administrative or Government Buildings 1979 - 2009_fossil',
 'IWU Office, Administrative or Government Buildings 1979 - 2009_hp',
 'IWU Office, Administrative or Government Buildings 2010 - 2030_biogene',
 'IWU Office, Administrative or Government Buildings 2010 - 2030_dh',
 'IWU Office, Administrative or Government Buildings 2010 - 2030_fossil',
 'IWU Office, Administrative or Government Buildings 2010 - 2030_hp',
 'IWU Production, Workshop, Warehouse or Operations (8) 1860 - 1978_biogene',
 'IWU Production, Workshop, Warehouse or Operations (8) 1860 - 1978_dh',
 'IWU Production, Workshop, Warehouse or Operations (8) 1860 - 1978_fossil',
 'IWU Production, Workshop, Warehouse or Operations (8) 1860 - 1978_hp',
 'IWU Production, Workshop, Warehouse or Operations (8) 1979 - 2009_biogene',
 'IWU Production, Workshop, Warehouse or Operations (8) 1979 - 2009_dh',
 'IWU Production, Workshop, Warehouse or Operations (8) 1979 - 2009_fossil',
 'IWU Production, Workshop, Warehouse or Operations (8) 1979 - 2009_hp',
 'IWU Production, Workshop, Warehouse or Operations (8) 2010 - 2030_biogene',
 'IWU Production, Workshop, Warehouse or Operations (8) 2010 - 2030_dh',
 'IWU Production, Workshop, Warehouse or Operations (8) 2010 - 2030_fossil',
 'IWU Production, Workshop, Warehouse or Operations (8) 2010 - 2030_hp',
 'IWU Trade Buildings (9) 1860 - 1978_biogene',
 'IWU Trade Buildings (9) 1860 - 1978_dh',
 'IWU Trade Buildings (9) 1860 - 1978_fossil',
 'IWU Trade Buildings (9) 1860 - 1978_hp',
 'IWU Trade Buildings (9) 1979 - 2009_biogene',
 'IWU Trade Buildings (9) 1979 - 2009_dh',
 'IWU Trade Buildings (9) 1979 - 2009_fossil',
 'IWU Trade Buildings (9) 1979 - 2009_hp',
 'IWU Trade Buildings (9) 2010 - 2030_biogene',
 'IWU Trade Buildings (9) 2010 - 2030_dh',
 'IWU Trade Buildings (9) 2010 - 2030_fossil',
 'IWU Trade Buildings (9) 2010 - 2030_reno_hp',
 'MWB I_Bis 1919_biogene',
 'MWB I_Bis 1919_dh',
 'MWB I_Bis 1919_fossil',
 'MWB I_Bis 1919_hp',
 'MWB I_Bis 1919_reno_biogene',
 'MWB I_Bis 1919_reno_dh',
 'MWB I_Bis 1919_reno_fossil',
 'MWB I_Bis 1919_reno_hp',
 'MWB II_1920-44_biogene',
 'MWB II_1920-44_dh',
 'MWB II_1920-44_fossil',
 'MWB II_1920-44_hp',
 'MWB II_1920-44_reno_biogene',
 'MWB II_1920-44_reno_dh',
 'MWB II_1920-44_reno_fossil',
 'MWB II_1920-44_reno_hp',
 'MWB III_1945-59_biogene',
 'MWB III_1945-59_dh',
 'MWB III_1945-59_fossil',
 'MWB III_1945-59_hp',
 'MWB III_1945-59_reno_biogene',
 'MWB III_1945-59_reno_dh',
 'MWB III_1945-59_reno_fossil',
 'MWB III_1945-59_reno_hp',
 'MWB IV_1960-79_biogene',
 'MWB IV_1960-79_dh',
 'MWB IV_1960-79_fossil',
 'MWB IV_1960-79_hp',
 'MWB IV_1960-79_reno_biogene',
 'MWB IV_1960-79_reno_dh',
 'MWB IV_1960-79_reno_fossil',
 'MWB IV_1960-79_reno_hp',
 'MWB V_1980-89_biogene',
 'MWB V_1980-89_dh',
 'MWB V_1980-89_fossil',
 'MWB V_1980-89_hp',
 'MWB V_1980-89_reno_biogene',
 'MWB V_1980-89_reno_dh',
 'MWB V_1980-89_reno_fossil',
 'MWB V_1980-89_reno_hp',
 'MWB VI_1990-99_biogene',
 'MWB VI_1990-99_dh',
 'MWB VI_1990-99_fossil',
 'MWB VI_1990-99_hp',
 'MWB VI_1990-99_reno_biogene',
 'MWB VI_1990-99_reno_dh',
 'MWB VI_1990-99_reno_fossil',
 'MWB VI_1990-99_reno_hp',
 'MWB VII_2000-20_biogene',
 'MWB VII_2000-20_dh',
 'MWB VII_2000-20_fossil',
 'MWB VII_2000-20_hp',
 'MWB VIII_>2020_biogene',
 'MWB VIII_>2020_dh',
 'MWB VIII_>2020_fossil',
 'MWB VIII_>2020_hp',
 'RH I_Bis 1919_biogene',
 'RH I_Bis 1919_dh',
 'RH I_Bis 1919_fossil',
 'RH I_Bis 1919_hp',
 'RH I_Bis 1919_reno_biogene',
 'RH I_Bis 1919_reno_dh',
 'RH I_Bis 1919_reno_fossil',
 'RH I_Bis 1919_reno_hp',
 'RH II_1920-44_biogene',
 'RH II_1920-44_dh',
 'RH II_1920-44_fossil',
 'RH II_1920-44_hp',
 'RH II_1920-44_reno_biogene',
 'RH II_1920-44_reno_dh',
 'RH II_1920-44_reno_fossil',
 'RH II_1920-44_reno_hp',
 'RH III_1945-59_biogene',
 'RH III_1945-59_dh',
 'RH III_1945-59_fossil',
 'RH III_1945-59_hp',
 'RH III_1945-59_reno_biogene',
 'RH III_1945-59_reno_dh',
 'RH III_1945-59_reno_fossil',
 'RH III_1945-59_reno_hp',
 'RH IV_1960-79_biogene',
 'RH IV_1960-79_dh',
 'RH IV_1960-79_fossil',
 'RH IV_1960-79_hp',
 'RH IV_1960-79_reno_biogene',
 'RH IV_1960-79_reno_dh',
 'RH IV_1960-79_reno_fossil',
 'RH IV_1960-79_reno_hp',
 'RH V_1980-89_biogene',
 'RH V_1980-89_dh',
 'RH V_1980-89_fossil',
 'RH V_1980-89_hp',
 'RH V_1980-89_reno_biogene',
 'RH V_1980-89_reno_dh',
 'RH V_1980-89_reno_fossil',
 'RH V_1980-89_reno_hp',
 'RH VI_1990-99_biogene',
 'RH VI_1990-99_dh',
 'RH VI_1990-99_fossil',
 'RH VI_1990-99_hp',
 'RH VI_1990-99_reno_biogene',
 'RH VI_1990-99_reno_dh',
 'RH VI_1990-99_reno_fossil',
 'RH VI_1990-99_reno_hp',
 'RH VII_2000-20_biogene',
 'RH VII_2000-20_dh',
 'RH VII_2000-20_fossil',
 'RH VII_2000-20_hp',
 'RH VIII_>2020_biogene',
 'RH VIII_>2020_dh',
 'RH VIII_>2020_fossil',
 'RH VIII_>2020_hp']

In [60]:

from archifer.parser import *

constraints = parse_yaml_config("../data/test_constraints.yaml")
constraints
for name, props in constraints.items():
    print(name, props)

Af_total {'type': 'equals', 'column': 'Af_m2', 'target': 878085}
Statcube_residential {'type': 'equals', 'column': 'Af_m2', 'filter': "residential=='yes'", 'target': 541379}
Statcube_residential2 {'type': 'greater than target', 'column': 'Af_m2', 'filter': ["residential=='yes'", "building_period=='bis 1919'"], 'target': 73302}

In [61]:
bs.archetypes["Af_m2"]["EFH I_Bis 1919_fossil"]

np.float64(210.08000000000004)

In [62]:
for name, props in constraints.items():
    bs.add_yaml_constraint(name, props)

In [63]:
a =[ "as"]
"+".join(a)

'as'

In [64]:
df.query("usage_simplified=='residential'")

UndefinedVariableError: name 'usage_simplified' is not defined

In [ ]:
data = pd.read_excel("../data/table_2026-01-12_11-55-55AT_NGFxBauperiode.xlsx", sheet_name="clean", index_col=0)

In [ ]:
data.head()

,Wohngebäude mit einer Wohnung,Wohngebäude mit zwei Wohnungen,Wohngebäude mit drei und mehr Wohnungen,Gebäude für Gemeinschaften,Hotels und ähnliche Gebäude,Bürogebäude,Groß- und Einzelhandelsgebäude,Gebäude des Verkehrs- und Nachrichtenwesens,Industrie- und Lagergebäude,Gebäude für Kultur- und Freizeitzwecke sowie des Bildungs- und Gesundheitswesens
Bauperiode,,,,,,,,,,
Vor 1919,23473512,10767691,39061683,2607298,8930436,12265087,6081724,1135984,9987208,11417429
1919 bis 1944,11723038,3849703,12527868,398091,1909084,2759625,1537935,443471,5410888,2506173
1945 bis 1960,18161803,7736326,17158733,690729,2977270,4531756,2556072,854886,8242364,4062368
1961 bis 1970,21762413,11347135,24662498,1321961,4736247,5438261,4864556,964407,11711618,6600796
1971 bis 1980,28584060,14142151,26287600,2126974,7340020,7922004,7261274,1414485,16454215,9158400

In [ ]:
tc = parse_yaml_config("../data/statcube_mappings.yaml")
tc

{'Bauperiode': {'type': 'rows',
  'archetype_field': 'building_period',
  'mapping': {'Vor 1919': ['bis 1919'],
   '1919 bis 1944': ['bis 1919', '1920-44'],
   '1945 bis 1960': ['1945-59', '1960-79'],
   '1961 bis 1970': ['1960-79'],
   '1971 bis 1980': ['1960-79', '1980-89'],
   '1981 bis 1990': ['1980-89', '1990-99'],
   '1991 bis 2000': ['1990-99', '2000-20'],
   '2001 bis 2005': ['2000-20'],
   '2006 bis 2010': ['2000-20'],
   '2011 bis 2015': ['2000-20'],
   '2016 und später': ['2000-20', 'ab 2020']}}}